### ISSUE TITLE
CREATE OR REPLACE VIEW

### ISSUE THREAD

**Issue by ruslansavenok** [devonestes/soft_delete_example#1]
I think this demo is missing a helper for updating the view after target table was modified:
```
alter table(:users) do
  add(:email, :string)
end
``` 

With the code above, view will not have email column. You'll need to execute create or replace:
```
CREATE OR REPLACE VIEW filtered.users AS
  SELECT * FROM users WHERE deleted_at IS NULL;
```

**Comment by ruslansavenok** [comment]
Also, there's a need for another helper if we want to modify column type:
```
    execute """
      DROP VIEW filtered.users;
    """

    alter table(:users) do
      modify(:email, :text)
    end

    execute """
      CREATE OR REPLACE VIEW filtered.users AS
        SELECT * FROM users WHERE deleted_at IS NULL;
    """
```

**Comment by devonestes** [comment]
This is an example of an implementation, not a library that one can or should use in production.

If you would like to write helper functions and publish them on hex, you're more than welcome to do so.
